name: Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            package-lock.json
          key: ${{ runner.OS }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-
      - name: Install Dependencies
        run: |
          npm uninstall hexo-renderer-marked --save  # 移除默认渲染器
          npm install hexo-renderer-markdown-it markdown-it-katex --save  # 安装新渲染器 + KaTeX 插件
          npm install  # 安装其他依赖
          npm install -g hexo-cli --unsafe-perm  # 全局安装 Hexo CLI
      - name: Build
        run: npx hexo generate
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4